<a href="https://colab.research.google.com/github/romenlongcode/YT-PYtorch/blob/main/intriopytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
import numpy as np
np1=np.random.rand(1,3)
np1

array([[0.04341479, 0.72953308, 0.90894442]])

In [5]:
np1.dtype

dtype('float64')

In [6]:
torch_t1=torch.rand(2,3)
torch_t1

tensor([[0.1082, 0.1332, 0.6539],
        [0.9673, 0.8982, 0.1194]])

In [ ]:
torch.dtype

torch.dtype

In [7]:
tensor_t2=torch.rand(3,3)
tensor_t2

tensor([[0.0045, 0.8213, 0.4265],
        [0.7840, 0.8498, 0.2682],
        [0.0875, 0.4575, 0.6186]])

In [ ]:
tensor_t2.dtype

torch.float32

In [8]:
type(tensor_t2)

torch.Tensor