<a href="https://colab.research.google.com/github/romenlongcode/YT-PYtorch/blob/main/intriopytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [9]:
import numpy as np
np1=np.random.rand(1,3)
np1

array([[0.48871097, 0.71153966, 0.39762289]])

In [10]:
np1.dtype

dtype('float64')

In [11]:
torch_t1=torch.rand(2,3)
torch_t1

tensor([[0.5694, 0.9640, 0.7886],
        [0.9514, 0.6369, 0.9837]])

In [12]:
torch.dtype

torch.dtype

In [13]:
tensor_t2=torch.rand(3,3)
tensor_t2

tensor([[0.1036, 0.9856, 0.6990],
        [0.4605, 0.5531, 0.3631],
        [0.5801, 0.7741, 0.8018]])

In [15]:
tensor_t2.dtype

torch.float32