<a href="https://colab.research.google.com/github/romenlongcode/YT-PYtorch/blob/main/tensoroperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [4]:
mytorch01= torch.arange(15)

In [5]:
mytorch02=mytorch01.reshape(3,-1)
mytorch02

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [7]:
mytorch02[:,0]

tensor([ 0,  5, 10])

In [8]:
mytorch02[:,1]

tensor([ 1,  6, 11])

In [9]:
mytorch02[:,2]

tensor([ 2,  7, 12])

In [10]:
mytorch02[:,3]

tensor([ 3,  8, 13])

In [12]:
mytorch02[:,3:]

tensor([[ 3,  4],
        [ 8,  9],
        [13, 14]])

In [13]:
mytorch02[:,3::]

tensor([[ 3,  4],
        [ 8,  9],
        [13, 14]])

In [21]:
#Tensor Mathematical Operations
#Addition

my_tensor1=torch.tensor([1,3,4,9,6])
my_tensor2=torch.tensor([2,5,3,8,9])

In [24]:
my_tensor3=my_tensor2+my_tensor1
my_tensor3

tensor([ 3,  8,  7, 17, 15])

In [ ]:
#SUBTRACTION
